baseURL = 'https://nqthqn.com/'
languageCode = 'en-us'
title = 'NQTHQN'
theme = 'hiya'

author = "Dirk Olbrich"
copyright = "Copyright © 2019, Dirk Olbrich, all rights reserved."



[params]
    name = "Hugo Tailwindcss Starter"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    github_user = "dirkolbrich"
    github_repo = "https://github.com/dirkolbrich/hugo-tailwindcss-starter-theme"
    github_banner = false

    debug = true

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
