[context.production.environment]
  HUGO_VERSION = "0.65.3"

[[redirects]]
  from = "https://nqthqn.com/notes/*"
  to = "https://publish.obsidian.md/serve?url=nqthqn.com/notes/:splat"
  status = 200
  force = true
